homeassistant:
  name: !secret name
  latitude: !secret tulacosm_la
  longitude: !secret tulacosm_lo
  elevation: !secret tulacosm_elevation
  unit_system: metric
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

#sensor: !include sensors.yaml
zone: !include zones.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

# UI Customizations
panel_iframe: !include side_panel.yaml
history:
logbook:
map:
cloud:
frontend:
config:
http:

# Core System
updater:
  include_used_components: true
discovery:
#    ignore:
#        - philips_hue
#        - harmony
recorder:
  db_url: !secret mysql_connstring

# Device Tracker
device_tracker:
  - platform: unifi
    host: !secret unifi_host
    username: !secret unifi_username
    password: !secret unifi_password
    verify_ssl: false
    site_id: !secret unifi_siteid
    new_device_defaults:
      track_new_devices: no
      hide_if_away: True